/uufs/astro.utah.edu/common/home/u1371365/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Traceback (most recent call last):
  File "/uufs/astro.utah.edu/common/home/u1371365/cloudKT/cloudKT.py", line 178, in <module>
    main()
  File "/uufs/astro.utah.edu/common/home/u1371365/cloudKT/cloudKT.py", line 40, in main
    logger_setup(program_directory + "/cloudKT.log")
  File "/uufs/astro.utah.edu/common/home/u1371365/cloudKT/cloudKT.py", line 163, in logger_setup
    fhandler = logging.FileHandler(log_file, mode="w")
  File "/uufs/chpc.utah.edu/sys/installdir/r8/python/3.10.3/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/uufs/chpc.utah.edu/sys/installdir/r8/python/3.10.3/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
FileNotFoundError: [Errno 2] No such file or directory: '/uufs/chpc.utah.edu/common/home/astro/zasowski/mcbride/modelfiles/cloudKT_alpha_runs/2025-02-28_alpha_runs--populate_from_files=true/cloudKT.log'
/uufs/astro.utah.edu/common/home/u1371365/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
2025-02-28 11:34:44,853 - Comment: same sightlines as 2025-02-26, but with sigma clip removed stars with chi2 < 2.
2025-02-28 11:34:44,853 - Running pipeline...
2025-02-28 11:34:44,854 - --- Loading Data ---
2025-02-28 11:34:46,543 - Loading star metadata...
2025-02-28 11:34:46,572 - Loading dust data...
2025-02-28 11:34:55,563 - Loading CO emission data...
2025-02-28 11:34:55,652 - Loading HI emission data...
2025-02-28 11:34:55,686 - Data loaded!
2025-02-28 11:34:55,686 - --- Loading sightline module ---
/uufs/astro.utah.edu/common/home/u1371365/cloudKT/residual_process.py:205: RuntimeWarning: invalid value encountered in divide
  res_corr = spectrum / model / medres_model
/uufs/astro.utah.edu/common/home/u1371365/.local/lib/python3.10/site-packages/numpy/core/fromnumeric.py:771: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/uufs/astro.utah.edu/common/home/u1371365/cloudKT/residual_process.py:205: RuntimeWarning: divide by zero encountered in divide
  res_corr = spectrum / model / medres_model
2025-02-28 11:35:36,459 - --- Running Model ---
2025-02-28 11:35:36,459 - Starting MCMC Setup...
2025-02-28 11:35:36,461 - Running MCMC for sightline 0...
2025-02-28 11:35:38,631 - Running MCMC...
2025-02-28 11:35:38,632 - N walkers updated to 485
